"""Update_ImportData_ChatThread

Revision ID: 113b3f0ae62a
Revises: ea01f64934f9
Create Date: 2025-09-05 20:30:08.084688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113b3f0ae62a'
down_revision: Union[str, Sequence[str], None] = 'ea01f64934f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImportData', sa.Column('Response', sa.String(), nullable=True))
    op.add_column('ImportData', sa.Column('DataSummary', sa.String(), nullable=True))
    op.add_column('ImportData', sa.Column('ThreadId', sa.UUID(), nullable=False))
    op.alter_column('ImportData', 'FileUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ImportData', 'UserId',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ImportData', 'CreatedBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key('fk_importdata_threadchats', 'ImportData', 'ChatThreads', ['ThreadId', 'UserId'], ['Id', 'UserId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_importdata_threadchats', 'ImportData', type_='foreignkey')
    op.alter_column('ImportData', 'CreatedBy',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ImportData', 'UserId',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ImportData', 'FileUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('ImportData', 'ThreadId')
    op.drop_column('ImportData', 'DataSummary')
    op.drop_column('ImportData', 'Response')
    # ### end Alembic commands ###
