"""Init

Revision ID: e5c3e542edfd
Revises: 
Create Date: 2025-08-14 22:46:40.957627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c3e542edfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('FirstName', sa.String(length=256), nullable=False),
    sa.Column('LastName', sa.String(length=256), nullable=False),
    sa.Column('Email', sa.String(length=256), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('CreatedBy', sa.UUID(), nullable=False),
    sa.Column('LastModifiedOn', sa.DateTime(timezone=True), nullable=True),
    sa.Column('LastModifiedBy', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name='pk_users_id')
    )
    op.create_index('ix_users_email', 'Users', ['Email'], unique=False)
    op.create_index('ix_users_id', 'Users', ['Id'], unique=False)
    op.create_index('ix_users_phonenumber', 'Users', ['PhoneNumber'], unique=False)
    op.create_table('ChatThreads',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('ThreadName', sa.String(length=256), nullable=True),
    sa.Column('CreatedBy', sa.UUID(), nullable=False),
    sa.Column('CreatedOn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LastModifiedBy', sa.UUID(), nullable=True),
    sa.Column('LastModifiedOn', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], name='fk_chatthreads_users'),
    sa.PrimaryKeyConstraint('Id', 'UserId', name='pk_chatthreads_id_userid')
    )
    op.create_index('ix_chatthreads_id', 'ChatThreads', ['Id'], unique=False)
    op.create_index('ix_chatthreads_userid', 'ChatThreads', ['UserId'], unique=False)
    op.create_table('ChatMessages',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('ThreadId', sa.UUID(), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('ChatRole', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', 'TOOL', name='ChatRoleEnum'), nullable=False),
    sa.Column('ChatMessage', sa.String(), nullable=False),
    sa.Column('SummerizeMessage', sa.String(), nullable=True),
    sa.Column('ResponseId', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.UUID(), nullable=False),
    sa.Column('CreatedOn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LastModifiedBy', sa.UUID(), nullable=True),
    sa.Column('LastModifiedOn', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ThreadId', 'UserId'], ['ChatThreads.Id', 'ChatThreads.UserId'], name='fk_chatmessages_threadchats'),
    sa.PrimaryKeyConstraint('Id', 'ThreadId', name='pk_chatmessages_id_threadid')
    )
    op.create_index('ix_chatmessages_id', 'ChatMessages', ['Id'], unique=False)
    op.create_index('ix_chatmessages_responseid', 'ChatMessages', ['ResponseId'], unique=False)
    op.create_index('ix_chatmessages_threadid', 'ChatMessages', ['ThreadId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatmessages_threadid', table_name='ChatMessages')
    op.drop_index('ix_chatmessages_responseid', table_name='ChatMessages')
    op.drop_index('ix_chatmessages_id', table_name='ChatMessages')
    op.drop_table('ChatMessages')
    op.execute("DROP TYPE IF EXISTS \"ChatRoleEnum\"")
    op.drop_index('ix_chatthreads_userid', table_name='ChatThreads')
    op.drop_index('ix_chatthreads_id', table_name='ChatThreads')
    op.drop_table('ChatThreads')
    op.drop_index('ix_users_phonenumber', table_name='Users')
    op.drop_index('ix_users_id', table_name='Users')
    op.drop_index('ix_users_email', table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
