"""create ImportData table

Revision ID: ea01f64934f9
Revises: e5c3e542edfd
Create Date: 2025-08-29 21:31:03.377234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea01f64934f9'
down_revision: Union[str, Sequence[str], None] = 'e5c3e542edfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImportData',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('FileName', sa.String(length=256), nullable=True),
    sa.Column('FileUrl', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('UserId', sa.UUID(), nullable=True),
    sa.Column('CreatedBy', sa.UUID(), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('LastModifiedBy', sa.UUID(), nullable=True),
    sa.Column('LastModifiedOn', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('Id', name='pk_importdata_id')
    )
    op.create_index(op.f('ix_ImportData_UserId'), 'ImportData', ['UserId'], unique=False)
    op.create_index('ix_importdata_id', 'ImportData', ['Id'], unique=False)
    op.create_index('ix_importdata_status_createdon', 'ImportData', ['Status', 'CreatedOn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_importdata_status_createdon', table_name='ImportData')
    op.drop_index('ix_importdata_id', table_name='ImportData')
    op.drop_index(op.f('ix_ImportData_UserId'), table_name='ImportData')
    op.drop_table('ImportData')
    # ### end Alembic commands ###
